name: health_steshkin
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  lints: ^2.0.1
  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.0
  firebase_auth: ^4.5.0
  firebase_core_desktop: ^1.0.2
  email_validator: '^2.1.16'
  cloud_firestore: ^4.7.1
  get: ^4.6.5
  line_awesome_flutter: ^2.0.0
  sizer: ^2.0.15
  animated_text_kit: ^4.2.2
  hive: ^2.2.3
  intl: ^0.17.0
  fl_chart: ^0.62.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.0
  build_runner: ^2.4.4
  path_provider: ^2.0.15
  calendar_appbar: ^0.0.6


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/image/logo.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/logo.png
    - assets/image/food.png
    - assets/image/sleep.png
    - assets/image/strength.png
    - assets/image/2.png
    - assets/image/3.png
    - assets/image/5.png
    - assets/image/6.png
    - assets/image/Low_workout.png
    - assets/image/top_workout.png
    - assets/image/fullbody.png
    - assets/image/workout_pages/water.png
    - assets/image/workout_pages/gan.png
    - assets/image/workout_pages/mat.png
    - assets/image/workout_pages/ot.png
    - assets/image/workout_pages/planka.png
    - assets/image/workout_pages/press.png
    - assets/image/workout_pages/bic.png
    - assets/image/workout_pages/jim.png
    - assets/image/workout_pages/w2.png
    - assets/image/workout_pages/w3.png
    - assets/image/workout_pages/rez.png
    - assets/image/workout_pages/gan2.png
    - assets/image/workout_pages/gan3.png
    - assets/image/workout_pages/v1.png
    - assets/image/workout_pages/jump.png
    - assets/image/workout_pages/stul.png
    - assets/image/workout_pages/walk.png
    - assets/image/workout_pages/running.gif
    - assets/image/workout_pages/cros.png
    - assets/image/workout_gym/barbell.png
    - assets/image/workout_gym/bpress.png
    - assets/image/workout_gym/pr.png
    - assets/image/workout_gym/pullups.png
    - assets/image/workout_gym/gym.png
    - assets/image/workout_gym/per.png
    - assets/image/workout_gym/pistol.png
    - assets/image/workout_gym/workm.png
    - assets/image/workout_gym/stun.png
    - assets/image/workout_gym/l1.png
    - assets/image/workout_gym/gl.png
    - assets/image/food_page/sunrise.png
    - assets/image/food_page/sun.png
    - assets/image/food_page/uj.png
    - assets/image/food_page/moon.png

  fonts:
     - family: Rubik
       fonts:
         - asset: assets/fonts/RubikDistressed-Regular.ttf
     - family: Ubuntu
       fonts:
         - asset: assets/fonts/UbuntuMono-Regular.ttf
         - asset: assets/fonts/UbuntuMono-Bold.ttf