// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_LZt0XY-kKxOtnAwXl1m8qNuGHFEDhRQ',
    appId: '1:531766623881:web:e368f650820b9f6834d058',
    messagingSenderId: '531766623881',
    projectId: 'diplomst',
    authDomain: 'diplomst.firebaseapp.com',
    storageBucket: 'diplomst.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY9gxFkN2iUTDSICa-EgfwmjIWJP1XKlY',
    appId: '1:531766623881:android:0dc544d18530988234d058',
    messagingSenderId: '531766623881',
    projectId: 'diplomst',
    storageBucket: 'diplomst.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfKId5-vujF6-HIHW1fb7a1tFdWE31jmE',
    appId: '1:531766623881:ios:b070c9c8358c4a3f34d058',
    messagingSenderId: '531766623881',
    projectId: 'diplomst',
    storageBucket: 'diplomst.appspot.com',
    iosClientId: '531766623881-jrtmor8so8fq8q9ep3tibolc7avq78p1.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthSteshkin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfKId5-vujF6-HIHW1fb7a1tFdWE31jmE',
    appId: '1:531766623881:ios:b070c9c8358c4a3f34d058',
    messagingSenderId: '531766623881',
    projectId: 'diplomst',
    storageBucket: 'diplomst.appspot.com',
    iosClientId: '531766623881-jrtmor8so8fq8q9ep3tibolc7avq78p1.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthSteshkin',
  );
}
